src/config/urls.py
import django
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
from core.views import (index,
                        page_not_founds,
                        server_error, Login,
                        Logout,
                        Registration,
                        send_test_email,
                        ActivateUser,
                        ProfileView,
                        EditProfileView)
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("accounts/profile/", ProfileView.as_view(), name="profile"),
    path("edit-profile/<int:pk>/", EditProfileView.as_view(), name="edit_profile"),
    path("", index, name="index"),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("send-email/", send_test_email, name="send_email"),
    path('oauth/', include('social_django.urls', namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = page_not_founds
handler500 = server_error

src/groups/urls.py
from django.urls import path

from groups.views import CreateGroupView, UpdateGroupView, AllGroupsView, DeleteGroupView, ShowGroupView

app_name = "groups"
urlpatterns = [
    path("", AllGroupsView.as_view(), name="all_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
    path("show/<int:pk>/", ShowGroupView.as_view(), name="show_group"),
]

src/students/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from students.views import AllStudentsView, CreateStudentView, UpdateStudentView, DeleteStudentView, get_resume

app_name = "students"
urlpatterns = [
    path("", AllStudentsView.as_view(), name="all_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", DeleteStudentView.as_view(), name="delete_student"),
    path("resume/<uuid:pk>", get_resume, name="get_resume"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/teachers/urls.py
from django.urls import path

from teachers.views import CreateTeachersView, UpdateTeacherView, AllTeachersView, DeleteTeacherView

app_name = "teachers"
urlpatterns = [
    path("", AllTeachersView.as_view(), name="all_teachers"),
    path("create/", CreateTeachersView.as_view(), name="create_teacher"),
    path("update/<int:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/templates/form_create.html
{% extends "main.html" %}
{% block meta %}
<meta name="description" content="{{ meta.description }}">
    <title>{{ meta.title }} </title>
{% endblock meta %}
{% block content %}
    <div class="d-flex justify-content-center">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table-dark">{{ form.as_table }}</table>
            <br>
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock content %}

src/templates/form_update.html
{% extends "main.html" %}
{% block meta %}
<meta name="description" content="{{ meta.description }}">
    <title>{{ meta.title }} </title>
{% endblock meta %}
{% block content %}
    <div class="d-flex justify-content-center">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table-dark">{{ form.as_table }}</table>
            <br>
            <input type="submit" value="Update">
        </form>
    </div>
{% endblock content %}

src/templates/index.html
{% extends "main.html" %}
{% load static %}
{% block meta %}
<meta name="description" content="{{ meta.description }}">
    <title>{{ meta.title }} </title>
{% endblock meta %}
{% block content %}
    <p>For test e-mail to mikolaz2727@gmail.com - <a href="{% url "send_email" %}">click here</a>  But you need login for it</p>
    <img src="{% static 'image/index.png' %}" alt="My image" class="img-fluid h-25 w-100">

{% endblock content %}

src/templates/main.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      {% block meta %}

      {% endblock meta %}

<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<link rel="canonical"
          href="https://getbootstrap.com/docs/5.2/examples/cover/">


    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    <!-- Custom styles for this template -->
    <link href="{% static '/css/cover.css' %} " rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="mb-auto">
      <div>
            <a class="nav-link fw-bold py-1 px-10 active" href="{% url "index" %}"><h3 class="float-md-start mb-0">LMS</h3></a>
            <nav class="nav nav-masthead justify-content-center float-md-end">
            <a class="nav-link fw-bold py-1 px-0 {% if page == 'students' %} active {% endif %} " aria-current="page" href="{% url "students:all_students" %}">Students</a> |
            <a class="nav-link fw-bold py-1 px-0 {% if page == 'teachers' %} active {% endif %} " href="{% url "teachers:all_teachers" %}"> Teachers </a> |
            <a class="nav-link fw-bold py-1 px-0 {% if page == 'groups' %} active {% endif %} " href="{% url "groups:all_groups" %}"> Groups</a>
            <a href="#"
                   class="nav-link fw-bold py-1 px-0 d-block link-dark text-decoration-none dropdown-toggle"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="mdo"
                         class="rounded-circle" width="32" height="32">
                </a>
                {% if user.is_authenticated %}
                    <ul class="dropdown-menu text-small" style="">
                        <li><p class="dropdown-item">{{ user.email }}</p></li>
                        <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                        {% if user.is_staff %}
                            <li><a class="dropdown-item" href="#">Admin
                                page</a>
                            </li>
                        {% endif %}
                        <li><a class="dropdown-item" href="#">Change password</a>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                        <li><a class="dropdown-item" href="{% url 'registration' %}">Registration</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Reset password</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'social:begin' 'google-oauth2' %}">Gmail</a></li>
                        <li><a class="dropdown-item" href="{% url 'social:begin' 'github' %}">GitHub</a></li>
                        <li><a class="dropdown-item" href="{% url 'social:begin' 'reddit' %}">Reddit</a></li>
                    </ul>
                {% endif %}
          </nav>
      </div>
      </header>

      <main class="px-3">
        <h1>
            {{ meta.h1 }}
        </h1>
          {% block content %}
          {% endblock content %}
      </main>

      <footer class="mt-auto text-white-50">
        <p>(c) Bastonc</p>
      </footer>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
  </body>
</html>

src/templates/profile.html
{% extends "main.html" %}
{% block meta %}
<meta name="description" content="{{ meta.description }}">
    <title>{{ meta.title }} </title>
{% endblock meta %}
{% block content %}
    {% load static %}
            <p>
                {% if user.profile.id %}
               <a class="btn btn-warning" href="{% url 'edit_profile' user.profile.id %}" role="button">Edit profile</a>
                {% endif %}
            </p>
            <p>Last Name: {{ user.last_name }}</p>
            <p>First Name: {{ user.first_name }}</p>
            <p>Email: {{ user.email }} </p>
            <p>Avatar: <img src="{% static user.profile.avatar %}" alt="Avatar" width="100"> </p>
            <p>Birth_date: {{ user.profile.birth_date }} </p>
            <p>Phone number: {{ user.profile.phone_number }} </p>
            <p>Social link: {{ user.profile.social_link }} </p>
            <p>Type person: {{ user.profile.type }} </p>
            <p>City: {{ user.profile.city }} </p>




    <img src="{% static 'image/1.png' %}" alt="My image" class="img-fluid h-25 w-100">
{% endblock content %}