src/config/urls.py
import django
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
from core.views import (index,
                        page_not_founds,
                        server_error, Login,
                        Logout,
                        Registration,
                        send_test_email,
                        ActivateUser,
                        ProfileView,
                        EditProfileView)
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("accounts/profile/", ProfileView.as_view(), name="profile"),
    path("edit-profile/<int:pk>/", EditProfileView.as_view(), name="edit_profile"),
    path("", index, name="index"),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("send-email/", send_test_email, name="send_email"),
    path('oauth/', include('social_django.urls', namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = page_not_founds
handler500 = server_error

src/groups/urls.py
from django.urls import path

from groups.views import CreateGroupView, UpdateGroupView, AllGroupsView, DeleteGroupView, ShowGroupView

app_name = "groups"
urlpatterns = [
    path("", AllGroupsView.as_view(), name="all_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
    path("show/<int:pk>/", ShowGroupView.as_view(), name="show_group"),
]

src/students/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from students.views import AllStudentsView, CreateStudentView, UpdateStudentView, DeleteStudentView, get_resume

app_name = "students"
urlpatterns = [
    path("", AllStudentsView.as_view(), name="all_students"),
    path("create/", CreateStudentView.as_view(), name="create_student"),
    path("update/<uuid:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<uuid:pk>/", DeleteStudentView.as_view(), name="delete_student"),
    path("resume/<uuid:pk>", get_resume, name="get_resume"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/students/models.py
from datetime import datetime
from uuid import uuid4

from django.core import validators
from django.utils import timezone
from django.db import models
from faker import Faker
from django.conf import settings
from core.models import Person


class Student(Person):
    ACTIVE = "Active"
    GRADUATE = "Graduate"
    EXPELLED = "Expelled"
    STATUS_STUDENT = [
        (ACTIVE, "Active student"),
        (GRADUATE, "Graduated successfully"),
        (EXPELLED, "Expelled from study"),
    ]

    uuid = models.UUIDField(
        primary_key=True,
        editable=False,
        default=uuid4,
        unique=True,
        db_index=True,
    )

    status = models.CharField(max_length=10, choices=STATUS_STUDENT, default=ACTIVE, blank=False)
    grade = models.PositiveSmallIntegerField(default=0, null=True)
    group = models.ForeignKey(to="groups.Groups", on_delete=models.CASCADE, null=True)
    avatar = models.ImageField(upload_to="image/students/", null=True)
    resume = models.FileField(
        upload_to="resume/students/",
        validators=[validators.FileExtensionValidator(["pdf", "doc"], message="Only PDF or DOC files")],
        null=True,
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email}"

    class Meta:
        verbose_name = "Student"
        verbose_name_plural = "All students"

    @classmethod
    def generate_students(cls, count):
        faker = Faker()

        for _ in range(count):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_time_between(start_date="-30y", end_date="-18y"),
                grade=faker.random.randint(0, 100),
            )

src/students/forms.py
from django.forms import ModelForm
from .models import Student
from django.core.validators import ValidationError


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = "__all__"

    def clean_email(self):
        email = self.cleaned_data["email"]
        if ".ru" in str(self.cleaned_data["email"]).lower():
            raise ValidationError("You can't use russian service of email")
        return email

    def clean_first_name(self):
        return self.clean_names(self.cleaned_data["first_name"])

    def clean_last_name(self):
        return self.clean_names((self.cleaned_data["last_name"]))

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]
        if first_name == last_name:
            raise ValidationError("Bro, you can't use equal First Name and Last Name. OK? Try Again! ")

    @staticmethod
    def clean_names(string_data: str) -> str:
        return string_data.strip().capitalize()

src/students/views.py
import uuid

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import FileResponse
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView, TemplateView

from .models import Student
from django.urls import reverse_lazy
from .forms import StudentForm


class CreateStudentView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("login")
    model = Student
    form_class = StudentForm
    template_name = "form_create.html"
    meta_page = {"title": "Create student | LMS", "description": "Create student form | LMS", "h1": "Create student"}
    extra_context = {"page": "student", "meta": meta_page}
    success_url = reverse_lazy("students:all_students")


class UpdateStudentView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy("login")
    model = Student
    form_class = StudentForm
    pk_url_kwarg = "pk"
    template_name = "form_update.html"
    meta_page = {"title": "Update student | LMS", "description": "Update student form | LMS", "h1": "Update student"}
    extra_context = {"page": "student", "meta": meta_page}
    success_url = reverse_lazy("students:all_students")


class DeleteStudentView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy("login")
    model = Student
    pk_url_kwarg = "pk"
    success_url = reverse_lazy("students:all_students")


class AllStudentsView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy("login")

    def get(self, request, *args, **kwargs):
        context = super().get_context_data()
        if request.GET.get("search"):
            student = Student.objects.filter(first_name=str(request.GET["search"]).strip().capitalize())
            context["meta"] = {
                "title": f"Search student {str(request.GET['search'])} | LMS",
                "description": "Search student | LMS",
                "h1": "Search students",
            }
            self.template_name = "students/student_search.html"
        else:
            student = Student.objects.all()
            context["meta"] = {"title": "All Student | LMS", "description": "All student | LMS", "h1": "Students"}
            self.template_name = "students/student_output.html"
        context["obj_from_db"] = student

        return self.render_to_response(context)


@login_required(login_url=reverse_lazy("login"))
def get_resume(request: object, pk: uuid.UUID):
    student = get_object_or_404(Student.objects.filter(pk=pk))
    return FileResponse(student.resume)

src/templates/students/student_confirm_delete.html
{% extends "main.html" %}
{% block meta %}
<meta name="description" content="">
    <title>Confirm delete</title>
{% endblock meta %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

src/templates/students/student_output.html
{% extends "main.html" %}
{% block meta %}
<meta name="description" content="{{ meta.description }}">
    <title>{{ meta.title }} </title>
{% endblock meta %}
{% block content %}
    {% load static %}
        <div class="d-flex justify-content-center">
        <form method="get">
            <div class="input-group mb-3">
                <input type="text" name="search" class="form-control" placeholder="First name" >
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </div>
            </div>
        </form>
        </div>
        <div class="d-flex justify-content-end">
            <a class="btn btn-success" href="{% url "students:create_student" %}" role="button">Add student</a>
        </div>

    <br>
    <table class="table table-dark table-hover">
    <thead>
    <tr><th scope="col">#</th><th scope="col">Avatar</th>
    <th scope="col">First name</th><th scope="col">Last name</th>
    <th scope="col">Email</th><th scope="col">Birthday</th>
    <th scope="col">Status</th><th scope="col">Grade</th>
    <th scope="col">Resume</th><th scope="col">Group</th>
    <th scope="col">Edit</th><th scope="col">Delete</th></tr>
    </thead>
    <tbody>
    {% for record in obj_from_db %}
    <tr><th scope="row">{{ forloop.counter }}</th><td><img  src="{% static record.avatar %}" height="100"></td><td>{{ record.first_name }}</td><td>{{ record.last_name }}</td>
        <td>{{ record.email }}</td><td>{{ record.birth_date }}</td><td>{{ record.status }}</td><td>{{ record.grade }}</td>
        <td><a class="btn btn-warning" href="{% url "students:get_resume" record.uuid %}" role="button">Resume</a></td>
        <td><a class="btn btn-warning" href="{% url "groups:show_group" record.group_id %}" role="button">Group</a></td>
        <td><a class="btn btn-warning" href="{% url "students:update_student" record.uuid %}" role="button">Edit</a></td>
        <td><a class="btn btn-danger" href="{% url "students:delete_student" record.uuid %}" role="button"><img src="{% static 'image/garbage.png' %}" alt="trash"></a></td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    <img src="{% static 'image/1.png' %}" alt="My image" class="img-fluid h-25 w-100">
{% endblock content %}

src/templates/students/student_search.html
{% extends "main.html" %}
{% block meta %}
<meta name="description" content="{{ meta.description }}">
    <title>{{ meta.title }} </title>
{% endblock meta %}
{% block content %}
    {% load static %}
        <div class="d-flex justify-content-center">
        <form method="get">
            <div class="input-group mb-3">
                <input type="text" name="search" class="form-control" placeholder="First name" value="{{ value }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </div>
            </div>
        </form>
        </div>
    {% if obj_from_db %}

    <table class="table table-dark table-hover">
    <thead>
    <tr><th scope="col">#</th><th scope="col">Avatar</th>
    <th scope="col">First name</th><th scope="col">Last name</th>
    <th scope="col">Email</th><th scope="col">Birthday</th>
    <th scope="col">Status</th><th scope="col">Grade</th>
    <th scope="col">Resume</th><th scope="col">Group</th>
    <th scope="col">Edit</th><th scope="col">Delete</th></tr>
    </thead>
    <tbody>
    {% for record in obj_from_db %}
    <tr><th scope="row">{{ forloop.counter }}</th><td><img  src="{% static record.avatar %}" height="100"></td><td>{{ record.first_name }}</td><td>{{ record.last_name }}</td>
        <td>{{ record.email }}</td><td>{{ record.birth_date }}</td><td>{{ record.status }}</td><td>{{ record.grade }}</td>
        <td><a class="btn btn-warning" href="{% url "students:get_resume" record.uuid %}" role="button">Resume</a></td>
        <td><a class="btn btn-warning" href="{% url "groups:show_group" record.group_id %}" role="button">Group</a></td>
        <td><a class="btn btn-warning" href="{% url "students:update_student" record.uuid %}" role="button">Edit</a></td>
        <td><a class="btn btn-danger" href="{% url "students:delete_student" record.uuid %}" role="button"><img src="{% static 'image/garbage.png' %}" alt="trash"></a></td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    {% else %}
    <br><h2> Sorry, but this student not found</h2>
    {% endif %}
    <img src="{% static 'image/1.png' %}" alt="My image" class="img-fluid h-25 w-100">
{% endblock content %}