src/config/urls.py
import django
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
from core.views import (index,
                        page_not_founds,
                        server_error, Login,
                        Logout,
                        Registration,
                        send_test_email,
                        ActivateUser,
                        ProfileView,
                        EditProfileView)
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("accounts/profile/", ProfileView.as_view(), name="profile"),
    path("edit-profile/<int:pk>/", EditProfileView.as_view(), name="edit_profile"),
    path("", index, name="index"),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("send-email/", send_test_email, name="send_email"),
    path('oauth/', include('social_django.urls', namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = page_not_founds
handler500 = server_error

src/groups/urls.py
from django.urls import path

from groups.views import CreateGroupView, UpdateGroupView, AllGroupsView, DeleteGroupView, ShowGroupView

app_name = "groups"
urlpatterns = [
    path("", AllGroupsView.as_view(), name="all_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
    path("show/<int:pk>/", ShowGroupView.as_view(), name="show_group"),
]

src/teachers/urls.py
from django.urls import path

from teachers.views import CreateTeachersView, UpdateTeacherView, AllTeachersView, DeleteTeacherView

app_name = "teachers"
urlpatterns = [
    path("", AllTeachersView.as_view(), name="all_teachers"),
    path("create/", CreateTeachersView.as_view(), name="create_teacher"),
    path("update/<int:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
]

src/teachers/models.py
import random
from uuid import uuid4

from django.db import models
from faker import Faker
from core.models import Person


class Teachers(Person):
    groups = models.ManyToManyField("groups.Groups")
    avatar = models.ImageField(upload_to="image/teachers/", null=True)

    @classmethod
    def generate_teachers(cls, amount):
        """
           Generate teachers from Faker
           :param count: int - amount teachers generated
           :return:
        """
        faker = Faker()
        for _ in range(amount):
            cls.objects.create(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                password=faker.password(),
                birth_date=faker.date_time_between(start_date="-50y", end_date="-25y"),
                phone=faker.phone_number(),
                programm_lang=random.choice(["Python", "PHP", "Perl", "Go", "C++"]),
                amount_group=1,
                practice_year=7,
            )

    def __str__(self):
        return f"id {self.id} name: {self.first_name} last name: {self.last_name}"

    class Meta:
        verbose_name = "Teacher"
        verbose_name_plural = "All Teachers"

src/teachers/forms.py
from django.forms import ModelForm
from .models import Teachers
from django.core.validators import ValidationError
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class TeacherForm(ModelForm):
    class Meta:
        model = Teachers
        fields = "__all__"

    def clean(self):
        clean_data = super().clean()
        clean_data["first_name"] = str(clean_data["first_name"]).capitalize()
        clean_data["last_name"] = str(clean_data["last_name"]).capitalize()
        if ".ru" in str(clean_data["email"]).lower():
            raise ValidationError("You can't use russian service of email")

src/teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView, TemplateView

from .models import Teachers
from django.urls import reverse_lazy
from .forms import TeacherForm


class CreateTeachersView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("login")
    model = Teachers
    form_class = TeacherForm
    template_name = "form_create.html"
    meta_page = {"title": "Create Teacher | LMS", "description": "Create teacher form | LMS", "h1": "Create teacher"}
    extra_context = {"page": "student", "meta": meta_page}
    success_url = reverse_lazy("teachers:all_teachers")


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy("login")
    model = Teachers
    form_class = TeacherForm
    pk_url_kwarg = "pk"
    template_name = "form_update.html"
    meta_page = {"title": "Update teacher | LMS", "description": "Update teacher form | LMS", "h1": "Update student"}
    extra_context = {"page": "teachers", "meta": meta_page}
    success_url = reverse_lazy("teachers:all_teachers")


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy("login")
    model = Teachers
    pk_url_kwarg = "pk"
    success_url = reverse_lazy("teachers:all_teachers")


class AllTeachersView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy("login")

    def get(self, request, *args, **kwargs):
        context = super().get_context_data()
        if request.GET.get("search"):
            teacher = Teachers.objects.filter(first_name=str(request.GET["search"]).strip().capitalize())
            context["meta"] = {
                "title": f"Search teacher {str(request.GET['search'])} | LMS",
                "description": "Search teacher | LMS",
                "h1": "Search teachers",
            }
            self.template_name = "teachers/teacher_search.html"
        else:

            teacher = Teachers.objects.all()
            context["meta"] = {"title": "All teacher | LMS", "description": "All teacher | LMS", "h1": "Teachers"}
            self.template_name = "teachers/output_teachers.html"
        context["obj_from_db"] = teacher
        return self.render_to_response(context)

src/templates/teachers/output_teachers.html
{% extends "main.html" %}
{% block meta %}
<meta name="description" content="{{ meta.description }}">
    <title>{{ meta.title }} </title>
{% endblock meta %}

{% block content %}
    {% load static %}
    <div class="">
        <div class="d-flex justify-content-center">
        <form method="get">
            <div class="input-group mb-3">
                <input type="text" name="search" class="form-control" placeholder="First name" >
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </div>
            </div>
        </form>
        </div>
        <div class="d-flex justify-content-end">
            <a class="btn btn-success" href="{% url "teachers:create_teacher" %}" role="button">Add teacher</a>
        </div>
    </div>
    <br>
    <table class="table table-dark table-hover">
    <thead>
    <tr><th scope="col">#</th><th scope="col">Avatar</th>
    <th scope="col">First name</th><th scope="col">Last name</th>
    <th scope="col">Email</th><th scope="col">Birthday</th>
    <th scope="col">Group(s)</th><th scope="col">Edit</th>
    <th scope="col">Delete</th></tr>
    </thead>
    <tbody>
    {% for record in obj_from_db %}
 
    <tr>
        <th scope="row">{{ forloop.counter }}</th><td><img  src="{% static record.avatar %}" height="100"></td><td>{{ record.first_name }}</td><td>{{ record.last_name }}</td>
        <td>{{ record.email }}</td><td>{{ record.birth_date}}</td>
        <td>

            {% for group in record.groups.all %}

                    <a class="btn btn-outline-info" style="--bs-btn-padding-y: .001rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem" href="{% url "groups:show_group" group.id %}" role="button">Group {{ group.id }}</a></br>

            {% endfor %}

        </td>
        <td><a class="btn btn-warning" href="{% url "teachers:update_teacher" record.id %}" role="button">Edit</a></td>
        <td><a class="btn btn-danger" href="{% url "teachers:delete_teacher" record.id %}" role="button"><img src="{% static 'image/garbage.png' %}" alt="trash"></a></td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    <img src="{% static 'image/1.png' %}" alt="My image" class="img-fluid h-25 w-100">
{% endblock content %}

src/templates/teachers/teacher_search.html
{% extends "main.html" %}
{% block meta %}
<meta name="description" content="{{ meta.description }}">
    <title>{{ meta.title }} </title>
{% endblock meta %}

{% block content %}
    {% load static %}
    <div class="">
        <div class="d-flex justify-content-center">
        <form method="get">
            <div class="input-group mb-3">
                <input type="text" name="search" class="form-control" placeholder="First name" value="{{ value }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </div>
            </div>
        </form>
        </div>
    </div>
    {% if obj_from_db %}
    <br>
    <table class="table table-dark table-hover">
    <thead>
    <tr><th scope="col">#</th><th scope="col">Avatar</th>
    <th scope="col">First name</th><th scope="col">Last name</th>
    <th scope="col">Email</th><th scope="col">Birthday</th>
    <th scope="col">Group(s)</th><th scope="col">Edit</th>
    <th scope="col">Delete</th></tr>
    </thead>
   <tbody>
    {% for record in obj_from_db %}

    <tr>
        <th scope="row">{{ forloop.counter }}</th><td><img  src="{% static record.avatar %}" height="100"></td><td>{{ record.first_name }}</td><td>{{ record.last_name }}</td>
        <td>{{ record.email }}</td><td>{{ record.birth_date}}</td>
        <td>

            {% for group in record.groups.all %}

                    <a class="btn btn-outline-info" style="--bs-btn-padding-y: .001rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem" href="{% url "groups:show_group" group.id %}" role="button">Group {{ group.id }}</a></br>

            {% endfor %}

        </td>
        <td><a class="btn btn-warning" href="{% url "teachers:update_teacher" record.id %}" role="button">Edit</a></td>
        <td><a class="btn btn-danger" href="{% url "teachers:delete_teacher" record.id %}" role="button"><img src="{% static 'image/garbage.png' %}" alt="trash"></a></td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    {% else %}
    <br><h2> Sorry, but this teacher not found</h2>
    {% endif %}
    <img src="{% static 'image/1.png' %}" alt="My image" class="img-fluid h-25 w-100">
{% endblock content %}

src/templates/teachers/teachers_confirm_delete.html
{% extends "main.html" %}
{% block meta %}
<meta name="description" content="">
    <title>Confirm delete</title>
{% endblock meta %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}