src/config/urls.py
import django
from django.contrib import admin
from django.template.defaulttags import url
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
from core.views import (index,
                        page_not_founds,
                        server_error, Login,
                        Logout,
                        Registration,
                        send_test_email,
                        ActivateUser,
                        ProfileView,
                        EditProfileView)
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("registration/", Registration.as_view(), name="registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("accounts/profile/", ProfileView.as_view(), name="profile"),
    path("edit-profile/<int:pk>/", EditProfileView.as_view(), name="edit_profile"),
    path("", index, name="index"),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("groups.urls")),
    path("send-email/", send_test_email, name="send_email"),
    path('oauth/', include('social_django.urls', namespace="social")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = page_not_founds
handler500 = server_error

src/groups/urls.py
from django.urls import path

from groups.views import CreateGroupView, UpdateGroupView, AllGroupsView, DeleteGroupView, ShowGroupView

app_name = "groups"
urlpatterns = [
    path("", AllGroupsView.as_view(), name="all_groups"),
    path("create/", CreateGroupView.as_view(), name="create_group"),
    path("update/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete/<int:pk>/", DeleteGroupView.as_view(), name="delete_group"),
    path("show/<int:pk>/", ShowGroupView.as_view(), name="show_group"),
]

src/groups/models.py
import random

from django.db import models

from faker import Faker
from django.conf import settings


class Groups(models.Model):
    PROGRAMM_LANG = settings.PROGRAMMING_LANG_TUPLE
    programm_lang = models.CharField(choices=PROGRAMM_LANG, default="Python", max_length=20, null=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    amount_student = models.PositiveSmallIntegerField(default=5, null=True)
    teacher_id = models.IntegerField(null=True)
    group_num = models.IntegerField(null=True)

    @classmethod
    def generate_groups(cls, amount):
        faker = Faker()
        for _ in range(amount):
            cls.objects.create(
                programm_lang="Python",
                start_date=faker.date_time_between(start_date="-10d"),
                end_date=faker.date_time_between(start_date="-10d"),
                amount_student=random.randint(5, 15),
                teacher_id=1,
                group_num=1,
            )

    def __str__(self):
        return f"{self.programm_lang}. Amount students: {self.amount_student}"

    class Meta:
        verbose_name = "Group"
        verbose_name_plural = "All groups"

src/groups/forms.py
from django.forms import ModelForm
from .models import Groups


class GroupForm(ModelForm):
    class Meta:
        model = Groups
        fields = (
            "programm_lang",
            "amount_student",
            "group_num",
            "teacher_id",
            "start_date",
            "end_date",
        )

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, TemplateView

from .models import Groups
from .forms import GroupForm


class CreateGroupView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("login")
    model = Groups
    form_class = GroupForm
    template_name = "form_create.html"
    meta_page = {"title": "Create group | LMS", "description": "Create group form | LMS", "h1": "Create student"}
    extra_context = {"page": "group", "meta": meta_page}
    success_url = reverse_lazy("groups:all_groups")


class UpdateGroupView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy("login")
    model = Groups
    form_class = GroupForm
    pk_url_kwarg = "pk"
    template_name = "form_update.html"
    meta_page = {"title": "Update group | LMS", "description": "Update group form | LMS", "h1": "Update student"}
    extra_context = {"page": "group", "meta": meta_page}
    success_url = reverse_lazy("groups:all_groups")


class DeleteGroupView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy("login")
    model = Groups
    pk_url_kwarg = "pk"
    success_url = reverse_lazy("groups:all_groups")


class AllGroupsView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy("login")
    template_name = "groups/output_groups.html"

    def get(self, request, *args, **kwargs):
        context = super().get_context_data()
        groups = Groups.objects.all()
        context["meta"] = {"title": "All Student | LMS", "description": "All student | LMS", "h1": "Students"}
        context["obj_from_db"] = groups
        return self.render_to_response(context)


class ShowGroupView(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy("login")
    template_name = "groups/show_group.html"

    def get(self, request, *args, **kwargs):
        context = super().get_context_data()
        group = get_object_or_404(Groups.objects.all(), pk=kwargs["pk"])
        context["meta"] = {"title": "Group info | LMS", "description": "Group info | LMS", "h1": "Group"}
        context["group"] = group
        return self.render_to_response(context)

src/templates/groups/groups_confirm_delete.html
{% extends "main.html" %}
{% block meta %}
<meta name="description" content="">
    <title>Confirm delete</title>
{% endblock meta %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

src/templates/groups/output_groups.html
{% extends "main.html" %}
{% load static %}
{% block meta %}
<meta name="description" content="{{ meta.description }}">
    <title>{{ meta.title }} </title>
{% endblock meta %}
{% block content %}

        <div class="d-flex justify-content-end">
            <a class="btn btn-success" href="{% url "groups:create_group" %}" role="button">Add group</a>
        </div>

    <br>
    <table class="table table-dark table-hover">
    <thead>
    <tr><th scope="col">#</th><th scope="col">ID</th>
    <th scope="col">Num group</th><th scope="col">Language</th>
    <th scope="col">Start date</th><th scope="col">Finish date</th>
    <th scope="col">Amount student</th>
    <th scope="col">Edit</th><th scope="col">Delete</th></tr>
    </thead>
    <tbody>
    {% for record in obj_from_db %}
    <tr>
        <td>{{ forloop.counter }}</td><td>{{ record.id }}</td><td>{{ record.group_num }}</td><td>{{ record.programm_lang  }}</td>
        <td>{{ record.start_date }}</td><td class="colM">{{ record.end_date}}</td><td>{{ record.amount_student }}</td>
        <td><a class="btn btn-warning" href="{% url "groups:update_group" record.id %}" role="button">Edit</a></td>
        <td><a class="btn btn-danger" href="{% url "groups:delete_group" record.id %}" role="button"><img src="{% static 'image/garbage.png' %}" alt="trash"></a></td>
    </tr>

    {% endfor %}
    </tbody>
    </table>
    <img src="{% static 'image/1.png' %}" alt="My image" class="img-fluid h-25 w-100">
{% endblock content %}

src/templates/groups/show_group.html
{% extends "main.html" %}
{% load static %}
{% block meta %}
<meta name="description" content="{{ meta.description }}">
    <title>{{ meta.title }} </title>
{% endblock meta %}
{% block content %}

        <div class="d-flex justify-content-end">
            <a class="btn btn-success" href="{% url "groups:create_group" %}" role="button">Add group</a>
        </div>

    <br>
    <table class="table table-dark table-hover">
    <thead>
    <tr><th scope="col">ID</th>
    <th scope="col">Group number</th><th scope="col">Language</th>
    <th scope="col">Date start course</th><th scope="col">Date finish course</th>
    <th scope="col">Edit</th><th scope="col">Delete</th></tr>
    </thead>
    <tbody>

    <tr>
        <td>{{ group.id }}</td><td>{{ group.group_num }}</td><td>{{ group.programm_lang  }}</td>
        <td>{{ group.start_date }}</td><td class="colM">{{ group.end_date}}</td>
        <td><a class="btn btn-warning" href="{% url "groups:update_group" group.id %}" role="button">Edit</a></td>
        <td><a class="btn btn-danger" href="{% url "groups:delete_group" group.id %}" role="button"><img src="{% static 'image/garbage.png' %}" alt="trash"></a></td>
    </tr>

    </tbody>
    </table>
    <img src="{% static 'image/1.png' %}" alt="My image" class="img-fluid h-25 w-100">
{% endblock content %}